file:
  version: 0.01beta
# In global section you can modify main setting
# settings.global.workspace - if name is set as `None`,
#
# Unix based system
# M1866 library will create workspace in default path: /home/{username}/.m1688/
# This config.yml of your local installation you'll could find in /home/{username}/.m1688/config.yml
#

settings:
  global:
    version: 1.0
    workspace: None
  templates:
    path:
